### ISSUE TITLE
Document `DEFINE-RESOURCE-DIRECTORY`

### ISSUE THREAD

**Issue by sjl** [Shinmera/deploy#1]
I'm trying to define a resource directory but can't figure out how.  I'll probably eventually get it if I bang my face on the keyboard enough, but I figured I'd add this for posterity.

> macro (DEFINE-RESOURCE-DIRECTORY NAME DIRECTORY &KEY (COPY-ROOT T))
> Shorthand to define a hook that simply deploys the given directory.

What is `name`?  Just an arbitrary symbol?

What is `directory`?  A string?  Lisp pathname thing?  Relative to the current path?  Absolute?

I have a directory called `assets` in my current folder that I'm trying to get copied to the resulting folder, so I'm trying this:

    (deploy:define-resource-directory assets "assets")

but that makes deploy explode like this:

```
 ==> Gathering system information.
   -> Will load the following foreign libs on boot:
      (#<DEPLOY:LIBRARY BEARLIBTERMINAL>)
 ==> Deploying files to /Users/sjl/src/rldt/bin/rldt.app/Contents/Resources/
While evaluating the form starting at line 19, column 0
  of #P"/Users/sjl/src/rldt/build/build-mac.lisp":

debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1001936E53}>:
  The value
    NIL
  is not of type
    (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME FILE-STREAM)
  when binding SB-IMPL::PATHSPEC
restarts (invokable by number or by possibly-abbreviated name):
  0: [REPORT-ERROR                 ] Print the error and continue running hooks.
  1: [RETRY                        ] Retry
                                     OSX-APP-DEPLOY-OP on #<SYSTEM "rldt">.
  2: [ACCEPT                       ] Continue, treating
                                     OSX-APP-DEPLOY-OP on #<SYSTEM "rldt"> as
                                     having been successful.
  3:                                 Retry ASDF operation.
  4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  5: [RETRY                        ] Retry EVAL of current toplevel form.
  6: [CONTINUE                     ] Ignore error and continue loading file "/Users/sjl/src/rldt/build/build-mac.lisp".
  7: [ABORT                        ] Abort loading file "/Users/sjl/src/rldt/build/build-mac.lisp".
  8:                                 Ignore runtime option --load "build/build-mac.lisp".
  9:                                 Skip rest of --eval and --load options.
 10:                                 Skip to toplevel READ/EVAL/PRINT loop.
 11: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(PATHNAME NIL) [external]
0] 
```

None of those restarts seem to give me a traceback, so I'm not sure where to look to track this down.

**Comment by sjl** [comment]
I told you I'd figure it out if I banged my face against the keyboard for a while.  The path has to end in a trailing slash, and also `define-resource-directory` was just broken.  See PR above.

**Comment by Shinmera** [comment]
The bug aside, I didn't figure it would actually be that confusing. It seems rather obvious to me that the name needs to be, well, a name for the hook it defines and the directory needs to be a pathname designator for the directory to copy.

I've clarified it a bit and changed the function to accept relative pathnames as well.
