### ISSUE TITLE
Foreign library dependencies

### ISSUE THREAD

**Issue by lockie** [Shinmera/deploy#10]
Hey.
Thanks for the wonderful library, I absolutely enjoy using it :)
However, I have a small problem with my particular setup.
I'm writing a library that uses [bodge-nuklear](https://github.com/borodust/bodge-nuklear), a wrapper around C library called nuklear. The problem is that for some reason it depends on two `.so` libraries, `libnuklear.so.bodged` and `libglad.so.bodged` (no idea why `.bodged` prefix, but that's not important), and the former depends on latter:
```
$ ldd src/bin/libnuklear.so.bodged
        linux-vdso.so.1 (0x00007fffe47a1000)
        libglad.so.bodged => not found
        libc.so.6 => /lib64/libc.so.6 (0x00007fd657396000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd65781b000)
```

Now, `deploy` perfectly detects both libraries and copies them in `bin/` directory, but when I launch the resulting executable, it crashes because it can't find the `libglad.so.bodged` library (because obviously `LD_LIBRARY_PATH` on unices does not include current directory unlike on windows):
```
 ==> Reloading foreign libraries.
   -> Loading foreign library #<LIBRARY LIBNUKLEAR.SO.BODGED-631>.
 ==> Encountered unhandled error: Unable to load foreign library (LIBNUKLEAR.SO.BODGED-631).
  Error opening shared object "/path/redacted/bin/libnuklear.so.bodged":
  libglad.so.bodged: cannot open shared object file: No such file or directory.
```
Of course I can workaround that by writing simple shell script that sets up `LD_LIBRARY_PATH` properly, but can it be done purely by lisp code means? I'm thinking maybe some sort of `:depends` keyword in `deploy:define-library` or something.

**Comment by Shinmera** [comment]
You can define a build hook that sorts `*foreign-libraries-to-reload*` to the proper order. It's true that a dependency system would be much more convenient, but I'd have to add that feature first.

**Comment by lockie** [comment]
All right, thanks, I'll try that.

**Comment by lockie** [comment]
Sorry for noobish question, I'm still new to CL ecosystem. While trying the workaround you've suggested, I'm getting either
` The symbol "*FOREIGN-LIBRARIES-TO-RELOAD*" is not external in the DEPLOY package.` or `The variable MY-PACKAGE::*FOREIGN-LIBRARIES-TO-RELOAD* is unbound.`. Seems like it has to do with that variable not being exported from `deploy`. How can I fix that?..

**Comment by Shinmera** [comment]
`deploy::*foreign-libraries-to-reload*`

**Comment by lockie** [comment]
Thanks a lot!
