### ISSUE TITLE
Cannot silence status messages anymore

### ISSUE THREAD

**Issue by iamFIREcracker** [Shinmera/deploy#17]
After this [commit](https://github.com/Shinmera/deploy/commit/8e804b2d163999801bcaa98fc27210b48a11abc6) I cannot generate a binary and have all the status messages silenced anymore.

I used to have the following in my build script:

```lisp
;; Disable :deploy status messages for the final binary
;; but enable it during the build process
(setf deploy:*status-output* nil)
(let ((deploy:*status-output* t))
  (asdf:make :cg :force t))
```

and it used to get the job done; but now, every time I execute the binary it would log a bunch of stuff on stderr:

```
$ ./bin/cg --version
 ==> Performing warm boot.
   -> Runtime directory is /Users/matteolandi/my-env/opt/cg/bin/
   -> Resource directory is /Users/matteolandi/my-env/opt/cg/bin/
 ==> Running boot hooks.
 ==> Reloading foreign libraries.
 ==> Launching application.
0.4.0-r61
```

Is there a way to disable the override introduced in that commit?

**Comment by m3m0ry** [comment]
I have an even more simple buildscript which has the same issue:
```cl
;; Disable :deploy status messages for the final binary
(setf deploy:*status-output* nil)
(asdf:make :my-app)
````
And yet, the first few lines of my binary are always:
```
==> Performing warm boot. -> Runtime directory is /server/factorio-simulator/factorio-simulator/bin/ -> Resource directory is /server/factorio-simulator/factorio-simulator/bin/ ==> Running boot hooks. ==> Reloading foreign libraries. ==> Launching application. 
```

**Comment by Shinmera** [comment]
95f56a314850a6c18fca26d45747c719f11b1123 (from a month ago) fixes this issue if you deploy as a non-gui app (meaning, :deploy-console is in *features*)

**Comment by b-tach** [comment]
I cannot figure out for the life of me how to set feature flags. Does this go somewhere in (asdf:defsystem ...), or (defpackage ...)? I am building the program from a makefile that makes sbcl eval (asdf:make :program-name). Everything works except I get the status output I am trying to silence somehow. I also note that I still learning common lisp and the things you can do with it.

**Comment by Shinmera** [comment]
Instead of doing that, you can also just `sbcl --eval '(push :deploy-console *features*)' --eval '(asdf:make :my-thingy)'`
