### ISSUE TITLE
How to silence status messages?

### ISSUE THREAD

**Issue by sjl** [Shinmera/deploy#4]
When I build a binary with deploy and run it, it spews a bunch of log messages to standard output like:

```
 ==> Performing warm boot.
   -> Runtime directory is /Users/sjl/src/brows/bin/
   -> Resource directory is /Users/sjl/src/brows/bin/
 ==> Running boot hooks.
 ==> Reloading foreign libraries.
   -> Loading foreign library #<LIBRARY LIBPANEL>.
   -> Loading foreign library #<LIBRARY LIBCURSES>.
 ==> Launching application.
hello
 ==> Epilogue.
 ==> Running quit hooks.
```

That's good for debugging the deployment, but bad for an actual utility that wants to print something to standard output for a user to read.  Is there a way to silence this output?  I looked in the code but didn't see anything obvious.

**Comment by Shinmera** [comment]
This tool was primarily geared towards UI apps, so I never thought about it much. Adding a switch for that shouldn't be a big deal though.

**Comment by sjl** [comment]
Perfect, thanks!

**Comment by Shinmera** [comment]
Reading the documentation for it helps
