### ISSUE TITLE
Wrong bin/ path for package inferred system

### ISSUE THREAD

**Issue by svetlyak40wt** [Shinmera/deploy#8]
When building a package-inferred system which specifies `:pathname` parameter in its `defsystem`, Deploy puts a binary into the bin directory inside the folder pointed by :pathname.

For example, having defsystem like this:

```lisp
(defsystem "lake"
  :class :package-inferred-system
  :pathname "src"
  :depends-on ("cl-syntax-interpol"
               "lake/main")
  :defsystem-depends-on (:deploy)
  :build-operation "deploy-op"
  :build-pathname "lake"
  :entry-point "lake/main:uiop-main")
```

and building this system, will create a binary `src/bin/lake`. However I'm expected it to be `bin/lake`, because documentation says that folder is created `within your project's root directory`.

This should be fixed somehow. Or if this behaviour is expected, the documentation should be fixed.

**Comment by Shinmera** [comment]
It seems this is ASDF's own behaviour for using the program-op. I guess I'll do my own logic, then.

**Comment by Shinmera** [comment]
Can you tell me what `(asdf:system-source-directory "lake")` tells you?

**Comment by svetlyak40wt** [comment]
```
CL-USER> (asdf:system-source-directory "lake")
#P"/Users/art/projects/lisp/lake/"
```

**Comment by Shinmera** [comment]
Please confirm ede17cc

**Comment by svetlyak40wt** [comment]
It works! Thank you!
