### ISSUE TITLE
Qtools Windows application is not saved with the .exe extension

### ISSUE THREAD

**Issue by phoe** [Shinmera/deploy#9]
Reproduced on Travis: https://travis-ci.com/phoe-trash/furcadia-post-splitter/jobs/249809158#L614

The resulting binary is not saved with the `.exe` extension.

**Comment by Shinmera** [comment]
This is fixed in 5b5367ace230aed31b0db7014cd74e8658f5e031

**Comment by phoe** [comment]
Thanks!
